DROP DATABASE IF EXISTS airflow;
DROP USER IF EXISTS airflow;
CREATE USER airflow WITH PASSWORD :'AIRFLOW_DB_PASSWORD';
CREATE DATABASE airflow;
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;
ALTER DATABASE airflow OWNER TO airflow;
